#!/bin/bash

# Compile TypeScript
npx tsc || { echo "Error: TypeScript compilation failed."; exit 1; }

# Run the Node.js server
echo "Done Compiling Tradesmith API! 🛠️"
node dist/index.js || { echo "Error: Unable to start server."; exit 1; }
