service: tradesmith-trader-api
provider:
  name: aws
  runtime: nodejs18.x
  deploymentBucket: tradesmith-trader-api-dev
  stage: dev
  region: eu-west-2
  memorySize: 128
functions:
  app:
    handler: app/app.handler
    events:
      - http: 
          path: /
          method: ANY
          cors: true
      - http: 
          path: /{proxy+}
          method: ANY
          cors: true
